### ISSUE TITLE
【网站失效】「大像素」网站链接变更

### ISSUE THREAD

**Issue by Keldos-Li** [xiangjianan/lks#10]
## 网站的完整名称：
大像素 | 千亿像素看中国

## 网站的URL（链接）：
在lks推荐页面中的原网址：http://bigpixel.cn/index.html
应当更正的正确网址：http://bigpixel.cn/zh-CN.html 

## 你是什么时候注意到该网站崩溃的？
2023年2月24日乱翻的时候。使用原先的链接跳转会进入施耐德电气的网页，不清楚是不是被劫持了……
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/23137268/221211130-9dff89c2-8b88-49ca-b957-aa8724710f1b.png">

另：如果你们的项目可以提pr的话，我也可以提pr……

**Comment by xiangjianan** [comment]
感谢反馈！网址已更新
